### ISSUE TITLE
cluttered namespace

### ISSUE THREAD

**Issue by goldingn** [steps-dev/steps#24]
There are quite a few things in the package namespace and therefore the documentation that don't need to be, and make it a little hard to navigate:

- You can unexport all the `is.something()` functions the user won't ever need
- You can consolidate the `egk_` data objects down to one object if you instead export a named list called `egk` then use e.g. `egk$mat`, `egk$mat_stoch` etc. (and then change the examples and vignettes)

**Comment by cvisintin** [comment]
All the is.something() functions are no longer exported
