### ISSUE TITLE
Feature request: Plot population size from time zero

### ISSUE THREAD

**Issue by geryan** [steps-dev/steps#29]
It would be great to have the option to plot the population from the initial population size, as well as/rather than the population after the first simulation.

I know this would require significant modification to the way the plot function operates now, e.g. by taking in the initial population raster as well.

E.g. this (my hacked version):
![Rplot01](https://user-images.githubusercontent.com/4963182/67989687-b6d97580-fc87-11e9-8d15-4c36e9485903.png)

As opposed to standard output:
![Rplot](https://user-images.githubusercontent.com/4963182/67989716-c953af00-fc87-11e9-81d3-d07bb0a9881a.png)

(The red emp line is also non-standard pls ignore)

(Also I know this is a bit dodgy as graph starts at time 1 not 0, soz)

**Comment by geryan** [comment]
Somewhat related might be including the initial timestep, suitability, carrying capacity etc in the first element of the `simulation_results` object output.

**Comment by cvisintin** [comment]
This would require storing the initial objects in the results object and then referring to them using a switch in the plot function. This is doable, but storing them sequentially will be problematic because indexing starts at one in R and they really need to be accessed from a 'zero' slot. If we stored them like this it would be confusing to users to access/subset the first timestep using a value of '2'.

**Comment by geryan** [comment]
Yes agreed. An alternative that wouldn't require restructure of the results object might be to allow the plot function to take either/or initial population sizes per stage, the initial total population and a stable state transition matrix and work out the initial population size for each stage under the hood (I have a hack function for this already: https://github.com/geryan/rfst/blob/8b8050b826a596500a2ce05edcb42e080b9ad3a5/R/functions/psr.R#L7, see args `p0` and `tm`), or the initial population rasters and do same?

It's not a big deal, but I find it weird that the population sequences don't start from the start.

**Comment by geryan** [comment]
Alternatively, name the timesteps in the results object, such that `results_object[[i]][[1]] == results_object[[i]]$timestep0` etc., so that although the index number is off, the name isnt, thus reducing some confusion?

**Comment by cvisintin** [comment]
We have revised the plotting functions - now all start from zero by storing the initial population, suitability and carrying capacity rasters as attributes of the simulation results object. See commit 7006cbe9e1c288d42f355a78ba2b2bdce2439afc
