### ISSUE TITLE
Description of arguments in ?modified_transition is backwards

### ISSUE THREAD

**Issue by geryan** [steps-dev/steps#31]
https://github.com/steps-dev/steps/blob/69c945325323dc0d8290c5a53747495ef3eceabb/R/growth_transition_functions-class.R#L33

Currently: 
`survival_layer`  the name of a spatial layer in the landscape object used to modify survival values (i.e. non-zero values in the first row).

`fecundity_layer`  the name of a spatial layer in the landscape object used to modify fecundity values (i.e. non-zero values in rows other than the first).

I think the (i.e. non-zero values ... ) should be the other way around?

**Comment by cvisintin** [comment]
Good pick-up - fixed in this commit:
https://github.com/steps-dev/steps/commit/b7915bd920508ca86c42aee27b7aeca8caabe3f4
