### ISSUE TITLE
Description of stochasticity input is a little confusing.

### ISSUE THREAD

**Issue by geryan** [steps-dev/steps#32]
https://github.com/steps-dev/steps/blob/69c945325323dc0d8290c5a53747495ef3eceabb/R/population_change-functions.R#L26

> Either scalar values or matrices (with the same dimension as transition_matrix) specifying the variability **(in standard deviations)** in the transition matrix either for populations in all grid cells (global_stochasticity) or for each grid cell population separately (local_stochasticity)

I think  **in standard deviations** is misleading, when the value supplied here **is** the standard deviation to the mean value supplied in the transition matrix, not some measure of a number of standard deviations which is implied by **in** standard deviations.

Alternate wording might be:
>Either scalar values or matrices (with the same dimension as transition_matrix) specifying the variability in the transition matrix either for populations in all grid cells (global_stochasticity) or for each grid cell population separately (local_stochasticity). Values supplied here are the standard deviation of a truncated normal distribution where the mean is the value supplied in the transition matrix.

**Comment by skiptoniam** [comment]
Aren't they the standard deviations of the corresponding mean transition rates. E.g I have a recorded five stage matrices in the field over x years. So we take the algorithmic mean and sd of these. If the sd are large, they are truncated to (0,1). But I always get confused about the difference between environment and demographic sd. I assume this environmental.

**Comment by cvisintin** [comment]
Yes, this is environmental. I have updated the documentation accordingly. Thanks for the suggestion.
