### ISSUE TITLE
Can't handle single mortality layer

### ISSUE THREAD

**Issue by geryan** [steps-dev/steps#33]
Mortality layer seems to need to be same length as `timesteps`, or at least not a single layer. Single layer produces:

> `10%Error: not a valid subset`

```
fire_1 <- egk_fire[[1]]

fire_mortal <- mortality(mortality_layer = "fire", stages = NULL)

ls <- landscape(population = egk_pop,
                suitability = egk_hab,
                carrying_capacity = egk_k,
                "fire" = fire_1)

pd <- population_dynamics(change = growth(egk_mat), modification = fire_mortal)

aa <- simulation(landscape = ls, population_dynamics = pd, habitat_dynamics = NULL, timesteps = 10)

>  |=========                                   |  10%Error: not a valid subset
```

_I realise it may not be a common application to have a mortality layer that means that the same proportion are killed in the same place every time, but 🤷 ._

**Comment by skiptoniam** [comment]
Can you just replicate the layer ntimes?

**Comment by geryan** [comment]
Oh you totally can.

Actually I've realised that the documentation for `mortality`  actually does specify

> number of layers must match the intended timesteps

Seems out of step with having a single static habitat layer or static other layer though (even though STEPS internally replicates these)

**Comment by cvisintin** [comment]
Was that a pun?

Again, this is a relic of the early API. We could internalise the 
duplication across all the functions but haven't gotten around to it yet.

Cheers,

Casey Visintin

Quantitative and Applied Ecology Group <http://qaeco.com>
School of BioSciences
University of Melbourne
Parkville | VIC 3010 | Australia
Mobile: 0434 424 084

P*Please consider the environment before printing this email*

**Comment by cvisintin** [comment]
OK, fixed in https://github.com/steps-dev/steps/commit/467c6ccbe67e88564f165285a0ed3d74a113e842
