### ISSUE TITLE
DESCRIPTION fields URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [steps-dev/steps#34]
Please consider adding fields 'URL' and 'BugReports' to the DESCRIPTION file to make it easy to find this repo from https://cran.r-project.org/package=steps and elsewhere.

**Comment by cvisintin** [comment]
These fields have been added for the next release. See https://github.com/steps-dev/steps/commit/467c6ccbe67e88564f165285a0ed3d74a113e842
