### ISSUE TITLE
ETA for next release? Removing defunct future::values()

### ISSUE THREAD

**Issue by HenrikBengtsson** [steps-dev/steps#35]
Hi, I'd like to remove defunct `values()` from **future** (https://github.com/HenrikBengtsson/future/issues/640) soon.  I noticed the CRAN version of **steps** imports it, but your development version here on GitHub has moved to `value()` [sic!].  Do you have an ETA for your next release?

**Comment by HenrikBengtsson** [comment]
Just a friendly reminder about this one. I'd like to be able to remove defunct `values()` from **future**. Your **steps** package is one of two blockers on CRAN.

**Comment by cvisintin** [comment]
Thanks for heads up. This is on my list and should be done before mid-October.

**Comment by HenrikBengtsson** [comment]
Hi, again. How's this going? The other package has now been updated and is on CRAN, meaning yours is the only one preventing **future** from dropping `values()`.

**Comment by HenrikBengtsson** [comment]
Oh, it looks like you've made an CRAN update to **steps** on 2022-10-04, which removed `values()` and replaced `multiprocess` too (https://github.com/cran/steps/commit/8bd488428344508e894dcfc784f71d59e0b31ad4)
